In [11]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# SQL Alchemy
from sqlalchemy import create_engine

# PyMySQL 
import pymysql
pymysql.install_as_MySQLdb()

# Imports the methods needed to abstract classes into tables
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()

# Allow us to declare column types
from sqlalchemy import Column, Integer, String, Float

In [12]:
# Create Engine and Pass in MySQL Connection
engine = create_engine('sqlite:///hawaii.db')

In [13]:
# inport csv data into pandas
hawaiidata = "clean_hawaii2.csv"

hawaii_df = pd.read_csv(hawaiidata)
hawaii_df.head(10)

,Unnamed: 0,station,date,prcp,tobs,name,latitude,longitude,elevation
0,0,USC00519397,2010-01-01,0.08,65,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
1,1,USC00519397,2010-01-02,0.00,63,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
2,2,USC00519397,2010-01-03,0.00,74,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
3,3,USC00519397,2010-01-04,0.00,76,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
4,5,USC00519397,2010-01-07,0.06,70,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
5,6,USC00519397,2010-01-08,0.00,64,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
6,7,USC00519397,2010-01-09,0.00,68,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
7,8,USC00519397,2010-01-10,0.00,73,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
8,9,USC00519397,2010-01-11,0.01,64,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
9,10,USC00519397,2010-01-12,0.00,61,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0

In [14]:
class Measurement(Base):
    __tablename__ = 'measurement_coll'
    id = Column(Integer, primary_key=True)
    item = Column(String(255))
    weight = Column(Float)
    collector = Column(String(255))

class Station(Base):
    __tablename__ = 'station_coll'
    id = Column(Integer)
    item = Column(String(255))
    weight = Column(Float)
    collector = Column(String(255))

ArgumentError: Mapper Mapper|Station|station_coll could not assemble any primary key columns for mapped table 'station_coll'