In [3]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [4]:
# inport vsv data into pandas
ha_measure = "hawaii_measurements.csv"
ha_stations = "hawaii_stations.csv"

hawaii_data1 = pd.read_csv(ha_measure)
hawaii_data2 = pd.read_csv(ha_stations)

In [5]:
hawaii_data1.head()

       station        date  prcp  tobs
0  USC00519397  2010-01-01  0.08    65
1  USC00519397  2010-01-02  0.00    63
2  USC00519397  2010-01-03  0.00    74
3  USC00519397  2010-01-04  0.00    76
4  USC00519397  2010-01-06   NaN    73

In [6]:
hawaii_data2.head()

,station,name,latitude,longitude,elevation
0,USC00519397,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
1,USC00513117,"KANEOHE 838.1, HI US",21.4234,-157.8015,14.6
2,USC00514830,"KUALOA RANCH HEADQUARTERS 886.9, HI US",21.5213,-157.8374,7.0
3,USC00517948,"PEARL CITY, HI US",21.3934,-157.9751,11.9
4,USC00518838,"UPPER WAHIAWA 874.3, HI US",21.4992,-158.0111,306.6

In [9]:
hawaii_full_df = pd.merge(hawaii_data1, hawaii_data2, on='station')
hawaii_full_df.head(20)

,station,date,prcp,tobs,name,latitude,longitude,elevation
0,USC00519397,2010-01-01,0.08,65,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
1,USC00519397,2010-01-02,0.00,63,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
2,USC00519397,2010-01-03,0.00,74,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
3,USC00519397,2010-01-04,0.00,76,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
4,USC00519397,2010-01-06,NaN,73,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
5,USC00519397,2010-01-07,0.06,70,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
6,USC00519397,2010-01-08,0.00,64,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
7,USC00519397,2010-01-09,0.00,68,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
8,USC00519397,2010-01-10,0.00,73,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
9,USC00519397,2010-01-11,0.01,64,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
10,USC00519397,2010-01-12,0.00,61,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
11,USC00519397,2010-01-14,0.00,66,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
12,USC00519397,2010-01-15,0.00,65,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
13,USC00519397,2010-01-16,0.00,68,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
14,USC00519397,2010-01-17,0.00,64,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
15,USC00519397,2010-01-18,0.00,72,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
16,USC00519397,2010-01-19,0.00,66,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
17,USC00519397,2010-01-20,0.00,66,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
18,USC00519397,2010-01-21,0.00,69,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
19,USC00519397,2010-01-22,0.00,67,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0

In [10]:
# hawaii_full_df.dropna(axis=, how='any')
newcleandf = hawaii_full_df[np.isfinite(hawaii_full_df['prcp'])]
print(newcleandf.isnull().sum())

station      0
date         0
prcp         0
tobs         0
name         0
latitude     0
longitude    0
elevation    0
dtype: int64

In [13]:
newcleandf
newcleandf.to_csv("clean_hawaii2.csv", encoding='utf-8')

In [15]:
newcleandf.reset_index()

,index,station,date,prcp,tobs,name,latitude,longitude,elevation
0,0,USC00519397,2010-01-01,0.08,65,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
1,1,USC00519397,2010-01-02,0.00,63,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
2,2,USC00519397,2010-01-03,0.00,74,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
3,3,USC00519397,2010-01-04,0.00,76,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
4,5,USC00519397,2010-01-07,0.06,70,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
5,6,USC00519397,2010-01-08,0.00,64,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
6,7,USC00519397,2010-01-09,0.00,68,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
7,8,USC00519397,2010-01-10,0.00,73,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
8,9,USC00519397,2010-01-11,0.01,64,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
9,10,USC00519397,2010-01-12,0.00,61,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
10,11,USC00519397,2010-01-14,0.00,66,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
11,12,USC00519397,2010-01-15,0.00,65,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
12,13,USC00519397,2010-01-16,0.00,68,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
13,14,USC00519397,2010-01-17,0.00,64,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
14,15,USC00519397,2010-01-18,0.00,72,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
15,16,USC00519397,2010-01-19,0.00,66,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
16,17,USC00519397,2010-01-20,0.00,66,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
17,18,USC00519397,2010-01-21,0.00,69,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
18,19,USC00519397,2010-01-22,0.00,67,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
19,20,USC00519397,2010-01-23,0.00,67,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
20,21,USC00519397,2010-01-24,0.01,71,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
21,22,USC00519397,2010-01-25,0.00,67,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
22,23,USC00519397,2010-01-26,0.04,76,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
23,24,USC00519397,2010-01-27,0.12,68,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
24,25,USC00519397,2010-01-28,0.00,72,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
25,27,USC00519397,2010-01-31,0.03,67,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
26,28,USC00519397,2010-02-01,0.01,66,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
27,30,USC00519397,2010-02-04,0.01,69,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
28,31,USC00519397,2010-02-05,0.00,67,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
29,32,USC00519397,2010-02-06,0.00,67,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3.0
...,...,...,...,...,...,...,...,...,...
18073,19513,USC00516128,2017-07-17,0.39,72,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18074,19514,USC00516128,2017-07-18,2.40,77,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18075,19515,USC00516128,2017-07-19,0.27,74,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18076,19516,USC00516128,2017-07-20,0.70,75,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18077,19517,USC00516128,2017-07-21,0.10,72,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18078,19518,USC00516128,2017-07-22,4.00,72,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18079,19519,USC00516128,2017-07-23,0.80,78,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18080,19520,USC00516128,2017-07-24,0.84,77,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18081,19521,USC00516128,2017-07-25,0.30,79,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18082,19522,USC00516128,2017-07-26,0.30,73,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18083,19523,USC00516128,2017-07-27,0.00,75,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18084,19524,USC00516128,2017-07-28,0.40,73,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18085,19525,USC00516128,2017-07-29,0.30,77,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18086,19526,USC00516128,2017-07-30,0.30,79,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18087,19527,USC00516128,2017-07-31,0.00,74,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18088,19529,USC00516128,2017-08-02,0.25,80,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18089,19530,USC00516128,2017-08-03,0.06,76,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18090,19533,USC00516128,2017-08-07,0.05,78,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18091,19534,USC00516128,2017-08-08,0.34,74,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18092,19535,USC00516128,2017-08-09,0.15,71,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18093,19536,USC00516128,2017-08-10,0.07,75,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18094,19538,USC00516128,2017-08-12,0.14,74,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18095,19540,USC00516128,2017-08-14,0.22,79,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18096,19541,USC00516128,2017-08-15,0.42,70,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18097,19542,USC00516128,2017-08-16,0.42,71,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18098,19543,USC00516128,2017-08-17,0.13,72,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18099,19545,USC00516128,2017-08-19,0.09,71,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18100,19547,USC00516128,2017-08-21,0.56,76,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18101,19548,USC00516128,2017-08-22,0.50,76,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4
18102,19549,USC00516128,2017-08-23,0.45,76,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4

In [18]:
?newcleandf.reset_index()